### ISSUE TITLE
Docs are generated with /// present

### ISSUE THREAD

**Issue by kerhong** [tailhook/quick-error#2]
When generating docs (cargo doc) documentation is included with ///

Example:

``` rust

/// Document outside quick_error
pub fn foo() {}

quick_error! {
    /// Document the overall error type
    #[derive(Debug)]
    pub enum ErrorType {
        /// Document first variant
        FirstVariant(e: i32) {
            from()
        }
        /// Document second variant
        SecondVariant {}
    }
}

```

expands to (can be seen with `cargo rustc -- -Z unstable-options --pretty=expanded`)

``` rust
/// Document outside quick_error
pub fn foo() {}

#[doc = "/// Document the overall error type"]
pub enum ErrorType {

    #[doc = "/// Document first variant"]
    FirstVariant(i32),

    #[doc = "/// Document second variant"]
    SecondVariant,
}

```

which leads to the generated html docs looking like

<pre><h3>Functions</h3><b>foo</b> Document outside quick_error<h3>Enums</h3><b>ErrorType</b> /// Document the overall error type<pre><h4>Variants</h4><b>FirstVariant</b> /// Document first variant
<b>SecondVariant</b> /// Document second variant</pre></pre>

**Comment by tailhook** [comment]
Well, it seems to be a bug of Rust 1.2 that is fixed in 1.3. I don't think I need to do anything to fix the bug in older rust. Can you confirm that bug is absent in Rust 1.3 for you?

**Comment by kerhong** [comment]
Rust 1.3 does indeed generate proper documentation.

**Comment by tailhook** [comment]
That's fine.
