### ISSUE TITLE
Allow wrapping of errors

### ISSUE THREAD

**Issue by Binero** [tailhook/quick-error#38]
It would be nice if something like this was possible: 
```rust
quick_error! {
    #[derive(Debug)]
    pub enum MagicHeaderParseError {
        Io(error: IoError) {
            description(error.description())
            display("{}", error.display())
            cause(error.cause())
            from(error: IoError) -> (error)
        }
    }
}
```

Right now this doesn't work, as `description(...)` only accepts string literals, and cause cannot take Options.

**Comment by tailhook** [comment]
Here is a [good example](https://github.com/tailhook/quick-error/issues/3#issue-114087570). The only issue is that cause isn't forwarded immediately. But I think the use case for `cause` is to walk through the whole chain anyway, so it shouldn't be a problem.

**Comment by Binero** [comment]
Thank you. I see. I guess this can be closed as a duplicate then.
