### ISSUE TITLE
File name and line number for error?

### ISSUE THREAD

**Issue by martinellison** [tailhook/quick-error#49]
Is there any way of getting file+line number into the error message?

**Comment by tailhook** [comment]
Sorry for the late reply. You're probably going to use either:
```rust
enum Error {
  SomeError { file: &'static str, line: usize }
}
return Err(SomeError { file: file!(), line: line!() })
```
Or the backtrace:
```rust
use backtrace::Backtrace;
enum Error {
  SomeError { backtrace: Backtrace }
}
return Err(SomeError { backtrace: Backtrace::new() })
```
We don't have any built-in helpers to make that easier. You can make a function for creating an error with a backtrace. Abstracting the file and line variant can only be via a macro though.

**Comment by tailhook** [comment]
And surely, you can put that into a format string, if that's what you're asking:
```rust
quick_error! {
    #[derive(Debug)]
    pub enum Error {
        MyError(file: &'static str, line: usize) {
            display("MyError at {}:{}", file, line)
        }
    }
}
```
